-- MySQL Script generated by MySQL Workbench
-- Wed Mar 22 18:46:55 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema bdd_apptrens
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bdd_apptrens
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bdd_apptrens` DEFAULT CHARACTER SET utf8 ;
USE `bdd_apptrens` ;

-- -----------------------------------------------------
-- Table `bdd_apptrens`.`Estacio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdd_apptrens`.`Estacio` (
  `idEstacio` INT NOT NULL,
  `nomEstacio` VARCHAR(100) NULL,
  `horariEstacio` VARCHAR(100) NULL,
  `localitzacioEstacio` VARCHAR(100) NULL,
  `telefonEstacio` INT NULL,
  PRIMARY KEY (`idEstacio`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdd_apptrens`.`Color`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdd_apptrens`.`Color` (
  `idColor` INT NOT NULL,
  `nomColor` VARCHAR(75) NULL,
  PRIMARY KEY (`idColor`),
  UNIQUE INDEX `nomColor_UNIQUE` (`nomColor` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdd_apptrens`.`Estacio_Colors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdd_apptrens`.`Estacio_Colors` (
  `Estacio_id` INT NOT NULL,
  `Color_id` INT NOT NULL,
  PRIMARY KEY (`Estacio_id`, `Color_id`),
  INDEX `fk_Estacio_Colors_Color1_idx` (`Color_id` ASC),
  CONSTRAINT `fk_Estacio_Colors_Estacio`
    FOREIGN KEY (`Estacio_id`)
    REFERENCES `bdd_appTrens`.`Estacio` (`idEstacio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Estacio_Colors_Color1`
    FOREIGN KEY (`Color_id`)
    REFERENCES `bdd_appTrens`.`Color` (`idColor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdd_apptrens`.`Tren`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdd_apptrens`.`Tren` (
  `idTren` INT NOT NULL,
  `nomTren` VARCHAR(45) NULL,
  `tipusTren` VARCHAR(45) NULL,
  PRIMARY KEY (`idTren`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdd_apptrens`.`Ruta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdd_apptrens`.`Ruta` (
  `idRuta` INT NOT NULL,
  `Color_id` INT NOT NULL,
  `Tren_id` INT NOT NULL,
  PRIMARY KEY (`idRuta`),
  INDEX `fk_Ruta_Color1_idx` (`Color_id` ASC),
  INDEX `fk_Ruta_Tren1_idx` (`Tren_id` ASC),
  CONSTRAINT `fk_Ruta_Color1`
    FOREIGN KEY (`Color_id`)
    REFERENCES `bdd_appTrens`.`Color` (`idColor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ruta_Tren1`
    FOREIGN KEY (`Tren_id`)
    REFERENCES `bdd_appTrens`.`Tren` (`idTren`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdd_apptrens`.`Tram`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdd_apptrens`.`Tram` (
  `idTram` INT NOT NULL,
  `hora` INT NULL,
  `minut` INT NULL,
  `Estacio_id` INT NULL,
  `Ruta_idRuta` INT NOT NULL,
  PRIMARY KEY (`idTram`),
  INDEX `fk_Tram_Estacio1_idx` (`Estacio_id` ASC),
  INDEX `fk_Tram_Ruta1_idx` (`Ruta_idRuta` ASC),
  CONSTRAINT `fk_Tram_Estacio1`
    FOREIGN KEY (`Estacio_id`)
    REFERENCES `bdd_appTrens`.`Estacio` (`idEstacio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Tram_Ruta1`
    FOREIGN KEY (`Ruta_idRuta`)
    REFERENCES `bdd_appTrens`.`Ruta` (`idRuta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdd_apptrens`.`Incidencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdd_apptrens`.`Incidencia` (
  `idIncidencia` INT NOT NULL,
  `descripcioIncidencia` VARCHAR(200) NULL,
  `retard` INT NULL,
  `activa` TINYINT NULL,
  `Ruta_id` INT NOT NULL,
  PRIMARY KEY (`idIncidencia`, `Ruta_id`),
  INDEX `fk_Incidencia_Ruta1_idx` (`Ruta_id` ASC),
  CONSTRAINT `fk_Incidencia_Ruta1`
    FOREIGN KEY (`Ruta_id`)
    REFERENCES `bdd_apptrens`.`Ruta` (`idRuta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
