INSERT INTO `estacio` (`idEstacio`,`nomEstacio`) VALUES (72400,'Aeroport');
INSERT INTO `estacio` (`idEstacio`,`nomEstacio`) VALUES (78505,'Aguilar de Segarra');
INSERT INTO `estacio` (`idEstacio`,`nomEstacio`) VALUES (73101,'Alcover');
INSERT INTO `estacio` (`idEstacio`,`nomEstacio`) VALUES (71502,'Altafulla-Tamarit');
INSERT INTO `estacio` (`idEstacio`,`nomEstacio`) VALUES (78407,'Anglesola');
INSERT INTO `estacio` (`idEstacio`,`nomEstacio`) VALUES (79600,'Arenys de Mar');
INSERT INTO `estacio` (`idEstacio`,`nomEstacio`) VALUES (71211,'Ascó');
INSERT INTO `estacio` (`idEstacio`,`nomEstacio`) VALUES (79404,'Badalona');
INSERT INTO `estacio` (`idEstacio`,`nomEstacio`) VALUES (77106,'Balenyà-Els Hostalets');
INSERT INTO `estacio` (`idEstacio`,`nomEstacio`) VALUES (77107,'Balenyà-Tona-Seva');
INSERT INTO `estacio` (`idEstacio`,`nomEstacio`) VALUES (78705,'Barberà del Vallès');
INSERT INTO `estacio` (`idEstacio`,`nomEstacio`) VALUES (78804,'Barcelona-Arc de Triomf');
INSERT INTO `estacio` (`idEstacio`,`nomEstacio`) VALUES (79009,'Barcelona-El Clot-Aragó');
INSERT INTO `estacio` (`idEstacio`,`nomEstacio`) VALUES (79400,'Barcelona-Estació de França');
INSERT INTO `estacio` (`idEstacio`,`nomEstacio`) VALUES (78806,'Barcelona-La Sagrera-Meridiana');
INSERT INTO `estacio` (`idEstacio`,`nomEstacio`) VALUES (71802,'Barcelona-Passeig de Gràcia');
INSERT INTO `estacio` (`idEstacio`,`nomEstacio`) VALUES (78805,'Barcelona-Plaça de Catalunya');
INSERT INTO `estacio` (`idEstacio`,`nomEstacio`) VALUES (78802,'Barcelona-Sant Andreu Arenal');
INSERT INTO `estacio` (`idEstacio`,`nomEstacio`) VALUES (79004,'Barcelona-Sant Andreu Comtal');
INSERT INTO `estacio` (`idEstacio`,`nomEstacio`) VALUES (71801,'Barcelona-Sants');
INSERT INTO `estacio` (`idEstacio`,`nomEstacio`) VALUES (78801,'Barcelona-Torre del Baró');
INSERT INTO `estacio` (`idEstacio`,`nomEstacio`) VALUES (78402,'Bell-lloc d\'Urgell');
INSERT INTO `estacio` (`idEstacio`,`nomEstacio`) VALUES (78406,'Bellpuig');
INSERT INTO `estacio` (`idEstacio`,`nomEstacio`) VALUES (71708,'Bellvitge');
INSERT INTO `estacio` (`idEstacio`,`nomEstacio`) VALUES (79606,'Blanes');
INSERT INTO `estacio` (`idEstacio`,`nomEstacio`) VALUES (79302,'Bordils-Juià');
INSERT INTO `estacio` (`idEstacio`,`nomEstacio`) VALUES (77112,'Borgonyà');
INSERT INTO `estacio` (`idEstacio`,`nomEstacio`) VALUES (79412,'Cabrera de Mar-Vilassar de Mar');
INSERT INTO `estacio` (`idEstacio`,`nomEstacio`) VALUES (78503,'Calaf');
INSERT INTO `estacio` (`idEstacio`,`nomEstacio`) VALUES (71601,'Calafell');
INSERT INTO `estacio` (`idEstacio`,`nomEstacio`) VALUES (79502,'Caldes d\'Estrac');
INSERT INTO `estacio` (`idEstacio`,`nomEstacio`) VALUES (79203,'Caldes de Malavella');
INSERT INTO `estacio` (`idEstacio`,`nomEstacio`) VALUES (79603,'Calella');
INSERT INTO `estacio` (`idEstacio`,`nomEstacio`) VALUES (79305,'Camallera');
INSERT INTO `estacio` (`idEstacio`,`nomEstacio`) VALUES (65403,'Camarles-Deltebre');
INSERT INTO `estacio` (`idEstacio`,`nomEstacio`) VALUES (65409,'Cambrils');
INSERT INTO `estacio` (`idEstacio`,`nomEstacio`) VALUES (65401,'Camp-redó');
INSERT INTO `estacio` (`idEstacio`,`nomEstacio`) VALUES (77301,'Campdevànol');
INSERT INTO `estacio` (`idEstacio`,`nomEstacio`) VALUES (79601,'Canet de Mar');
INSERT INTO `estacio` (`idEstacio`,`nomEstacio`) VALUES (71302,'Capçanes');
INSERT INTO `estacio` (`idEstacio`,`nomEstacio`) VALUES (79101,'Cardedeu');
INSERT INTO `estacio` (`idEstacio`,`nomEstacio`) VALUES (78605,'Castellbell i el Vilar-Monistrol de Mont');
INSERT INTO `estacio` (`idEstacio`,`nomEstacio`) VALUES (72210,'Castellbisbal');
INSERT INTO `estacio` (`idEstacio`,`nomEstacio`) VALUES (71705,'Castelldefels');
INSERT INTO `estacio` (`idEstacio`,`nomEstacio`) VALUES (78405,'Castellnou de Seana');
INSERT INTO `estacio` (`idEstacio`,`nomEstacio`) VALUES (79301,'Celrà');
INSERT INTO `estacio` (`idEstacio`,`nomEstacio`) VALUES (77105,'Centelles');
INSERT INTO `estacio` (`idEstacio`,`nomEstacio`) VALUES (79316,'Cerbère');
INSERT INTO `estacio` (`idEstacio`,`nomEstacio`) VALUES (78706,'Cerdanyola del Vallès');
INSERT INTO `estacio` (`idEstacio`,`nomEstacio`) VALUES (72503,'Cerdanyola-Universitat');
INSERT INTO `estacio` (`idEstacio`,`nomEstacio`) VALUES (78500,'Cervera');
INSERT INTO `estacio` (`idEstacio`,`nomEstacio`) VALUES (79314,'Colera');
INSERT INTO `estacio` (`idEstacio`,`nomEstacio`) VALUES (72303,'Cornellà');
INSERT INTO `estacio` (`idEstacio`,`nomEstacio`) VALUES (71604,'Cubelles');
INSERT INTO `estacio` (`idEstacio`,`nomEstacio`) VALUES (71603,'Cunit');
INSERT INTO `estacio` (`idEstacio`,`nomEstacio`) VALUES (71305,'Duesaigües-L\'Argentera');
INSERT INTO `estacio` (`idEstacio`,`nomEstacio`) VALUES (79407,'El Masnou');
INSERT INTO `estacio` (`idEstacio`,`nomEstacio`) VALUES (72211,'El Papiol');
INSERT INTO `estacio` (`idEstacio`,`nomEstacio`) VALUES (71707,'El Prat de Llobregat');
INSERT INTO `estacio` (`idEstacio`,`nomEstacio`) VALUES (72201,'El Vendrell');
INSERT INTO `estacio` (`idEstacio`,`nomEstacio`) VALUES (71301,'Els Guiamets');
INSERT INTO `estacio` (`idEstacio`,`nomEstacio`) VALUES (72203,'Els Monjos');
INSERT INTO `estacio` (`idEstacio`,`nomEstacio`) VALUES (77103,'Figaró');
INSERT INTO `estacio` (`idEstacio`,`nomEstacio`) VALUES (79309,'Figueres');
INSERT INTO `estacio` (`idEstacio`,`nomEstacio`) VALUES (79303,'Flaçà');
INSERT INTO `estacio` (`idEstacio`,`nomEstacio`) VALUES (79205,'Fornells de la Selva');
INSERT INTO `estacio` (`idEstacio`,`nomEstacio`) VALUES (71210,'Flix');
INSERT INTO `estacio` (`idEstacio`,`nomEstacio`) VALUES (71703,'Garraf');
INSERT INTO `estacio` (`idEstacio`,`nomEstacio`) VALUES (71706,'Gavà');
INSERT INTO `estacio` (`idEstacio`,`nomEstacio`) VALUES (72208,'Gelida');
INSERT INTO `estacio` (`idEstacio`,`nomEstacio`) VALUES (79300,'Girona');
INSERT INTO `estacio` (`idEstacio`,`nomEstacio`) VALUES (78404,'Golmés');
INSERT INTO `estacio` (`idEstacio`,`nomEstacio`) VALUES (79100,'Granollers Centre');
INSERT INTO `estacio` (`idEstacio`,`nomEstacio`) VALUES (77006,'Granollers-Canovelles');
INSERT INTO `estacio` (`idEstacio`,`nomEstacio`) VALUES (79105,'Gualba');
INSERT INTO `estacio` (`idEstacio`,`nomEstacio`) VALUES (79107,'Hostalric');
INSERT INTO `estacio` (`idEstacio`,`nomEstacio`) VALUES (73002,'Juneda');
INSERT INTO `estacio` (`idEstacio`,`nomEstacio`) VALUES (65402,'L\'Aldea-Amposta');
INSERT INTO `estacio` (`idEstacio`,`nomEstacio`) VALUES (65405,'L\'Ametlla de Mar');
INSERT INTO `estacio` (`idEstacio`,`nomEstacio`) VALUES (65404,'L\'Ampolla-Perelló-Deltebre');
INSERT INTO `estacio` (`idEstacio`,`nomEstacio`) VALUES (72202,'L\'Arboç');
INSERT INTO `estacio` (`idEstacio`,`nomEstacio`) VALUES (72305,'L\'Hospitalet de Llobregat');
INSERT INTO `estacio` (`idEstacio`,`nomEstacio`) VALUES (73007,'L\'Espluga de Francolí');
INSERT INTO `estacio` (`idEstacio`,`nomEstacio`) VALUES (65407,'L\'Hospitalet de l\'Infant');
INSERT INTO `estacio` (`idEstacio`,`nomEstacio`) VALUES (77114,'La Farga de Bebié');
INSERT INTO `estacio` (`idEstacio`,`nomEstacio`) VALUES (73004,'La Floresta');
INSERT INTO `estacio` (`idEstacio`,`nomEstacio`) VALUES (77102,'La Garriga');
INSERT INTO `estacio` (`idEstacio`,`nomEstacio`) VALUES (77306,'La Molina');
INSERT INTO `estacio` (`idEstacio`,`nomEstacio`) VALUES (72205,'La Granada');
INSERT INTO `estacio` (`idEstacio`,`nomEstacio`) VALUES (79011,'La Llagosta');
INSERT INTO `estacio` (`idEstacio`,`nomEstacio`) VALUES (73100,'La Plana-Picamoixons');
INSERT INTO `estacio` (`idEstacio`,`nomEstacio`) VALUES (73010,'La Riba');
INSERT INTO `estacio` (`idEstacio`,`nomEstacio`) VALUES (73102,'La Selva del Camp');
INSERT INTO `estacio` (`idEstacio`,`nomEstacio`) VALUES (77310,'La Tor de Querol-Enveig');
INSERT INTO `estacio` (`idEstacio`,`nomEstacio`) VALUES (73003,'Les Borges Blanques');
INSERT INTO `estacio` (`idEstacio`,`nomEstacio`) VALUES (72206,'Lavern-Subirats');
INSERT INTO `estacio` (`idEstacio`,`nomEstacio`) VALUES (77100,'Les Franqueses del Vallès');
INSERT INTO `estacio` (`idEstacio`,`nomEstacio`) VALUES (71307,'Les Borges del Camp');
INSERT INTO `estacio` (`idEstacio`,`nomEstacio`) VALUES (79109,'Les Franqueses-Granollers Nord');
INSERT INTO `estacio` (`idEstacio`,`nomEstacio`) VALUES (79312,'Llançà');
INSERT INTO `estacio` (`idEstacio`,`nomEstacio`) VALUES (78400,'Lleida-Pirineus');
INSERT INTO `estacio` (`idEstacio`,`nomEstacio`) VALUES (79605,'Malgrat de Mar');
INSERT INTO `estacio` (`idEstacio`,`nomEstacio`) VALUES (79102,'Llinars del Vallès');
INSERT INTO `estacio` (`idEstacio`,`nomEstacio`) VALUES (77110,'Manlleu');
INSERT INTO `estacio` (`idEstacio`,`nomEstacio`) VALUES (71303,'Marçà-Falset');
INSERT INTO `estacio` (`idEstacio`,`nomEstacio`) VALUES (72209,'Martorell');
INSERT INTO `estacio` (`idEstacio`,`nomEstacio`) VALUES (78600,'Manresa');
INSERT INTO `estacio` (`idEstacio`,`nomEstacio`) VALUES (79500,'Mataró');
INSERT INTO `estacio` (`idEstacio`,`nomEstacio`) VALUES (79200,'Maçanet-Massanes');
INSERT INTO `estacio` (`idEstacio`,`nomEstacio`) VALUES (72300,'Molins de Rei');
INSERT INTO `estacio` (`idEstacio`,`nomEstacio`) VALUES (78403,'Mollerussa');
INSERT INTO `estacio` (`idEstacio`,`nomEstacio`) VALUES (79006,'Mollet-Sant Fost');
INSERT INTO `estacio` (`idEstacio`,`nomEstacio`) VALUES (77004,'Mollet-Santa Rosa');
INSERT INTO `estacio` (`idEstacio`,`nomEstacio`) VALUES (65408,'Mont-roig del Camp');
INSERT INTO `estacio` (`idEstacio`,`nomEstacio`) VALUES (73008,'Montblanc');
INSERT INTO `estacio` (`idEstacio`,`nomEstacio`) VALUES (78800,'Montcada Bifurcació');
INSERT INTO `estacio` (`idEstacio`,`nomEstacio`) VALUES (77002,'Montcada Ripollet');
INSERT INTO `estacio` (`idEstacio`,`nomEstacio`) VALUES (79005,'Montcada i Reixac');
INSERT INTO `estacio` (`idEstacio`,`nomEstacio`) VALUES (78708,'Montcada i Reixac-Manresa');
INSERT INTO `estacio` (`idEstacio`,`nomEstacio`) VALUES (78707,'Montcada i Reixac-Santa Maria');
INSERT INTO `estacio` (`idEstacio`,`nomEstacio`) VALUES (79405,'Montgat');
INSERT INTO `estacio` (`idEstacio`,`nomEstacio`) VALUES (79406,'Montgat Nord');
INSERT INTO `estacio` (`idEstacio`,`nomEstacio`) VALUES (79007,'Montmeló');
INSERT INTO `estacio` (`idEstacio`,`nomEstacio`) VALUES (71300,'Móra la Nova');
INSERT INTO `estacio` (`idEstacio`,`nomEstacio`) VALUES (76003,'Nulles-Bràfim');
INSERT INTO `estacio` (`idEstacio`,`nomEstacio`) VALUES (79408,'Ocata');
INSERT INTO `estacio` (`idEstacio`,`nomEstacio`) VALUES (79103,'Palautordera');
INSERT INTO `estacio` (`idEstacio`,`nomEstacio`) VALUES (77005,'Parets del Vallès');
INSERT INTO `estacio` (`idEstacio`,`nomEstacio`) VALUES (79604,'Pineda de Mar');
INSERT INTO `estacio` (`idEstacio`,`nomEstacio`) VALUES (77304,'Planoles');
INSERT INTO `estacio` (`idEstacio`,`nomEstacio`) VALUES (71704,'Platja de Castelldefels');
INSERT INTO `estacio` (`idEstacio`,`nomEstacio`) VALUES (79315,'Portbou');
INSERT INTO `estacio` (`idEstacio`,`nomEstacio`) VALUES (65411,'Port Aventura');
INSERT INTO `estacio` (`idEstacio`,`nomEstacio`) VALUES (71304,'Pradell');
INSERT INTO `estacio` (`idEstacio`,`nomEstacio`) VALUES (79409,'Premià de Mar');
INSERT INTO `estacio` (`idEstacio`,`nomEstacio`) VALUES (77309,'Puigcerdà');
INSERT INTO `estacio` (`idEstacio`,`nomEstacio`) VALUES (73001,'Puigverd de Lleida-Artesa de Lleida');
INSERT INTO `estacio` (`idEstacio`,`nomEstacio`) VALUES (78506,'Rajadell');
INSERT INTO `estacio` (`idEstacio`,`nomEstacio`) VALUES (71400,'Reus');
INSERT INTO `estacio` (`idEstacio`,`nomEstacio`) VALUES (71209,'Riba-roja d\'Ebre');
INSERT INTO `estacio` (`idEstacio`,`nomEstacio`) VALUES (77303,'Ribes de Freser');
INSERT INTO `estacio` (`idEstacio`,`nomEstacio`) VALUES (79106,'Riells i Viabrea-Breda');
INSERT INTO `estacio` (`idEstacio`,`nomEstacio`) VALUES (77200,'Ripoll');
INSERT INTO `estacio` (`idEstacio`,`nomEstacio`) VALUES (71306,'Riudecanyes-Botarell');
INSERT INTO `estacio` (`idEstacio`,`nomEstacio`) VALUES (79204,'Riudellots');
INSERT INTO `estacio` (`idEstacio`,`nomEstacio`) VALUES (72100,'Roda de Barà');
INSERT INTO `estacio` (`idEstacio`,`nomEstacio`) VALUES (72101,'Roda de Mar');
INSERT INTO `estacio` (`idEstacio`,`nomEstacio`) VALUES (72501,'Rubí');
INSERT INTO `estacio` (`idEstacio`,`nomEstacio`) VALUES (78704,'Sabadell Centre');
INSERT INTO `estacio` (`idEstacio`,`nomEstacio`) VALUES (78709,'Sabadell Nord');
INSERT INTO `estacio` (`idEstacio`,`nomEstacio`) VALUES (78703,'Sabadell Sud');
INSERT INTO `estacio` (`idEstacio`,`nomEstacio`) VALUES (76001,'Salomó');
INSERT INTO `estacio` (`idEstacio`,`nomEstacio`) VALUES (65410,'Salou');
INSERT INTO `estacio` (`idEstacio`,`nomEstacio`) VALUES (79403,'Sant Adrià del Besòs');
INSERT INTO `estacio` (`idEstacio`,`nomEstacio`) VALUES (79501,'Sant Andreu de Llavaneres');
INSERT INTO `estacio` (`idEstacio`,`nomEstacio`) VALUES (79104,'Sant Celoni');
INSERT INTO `estacio` (`idEstacio`,`nomEstacio`) VALUES (72502,'Sant Cugat del Vallès');
INSERT INTO `estacio` (`idEstacio`,`nomEstacio`) VALUES (72301,'Sant Feliu de Llobregat');
INSERT INTO `estacio` (`idEstacio`,`nomEstacio`) VALUES (78501,'Sant Guim de Freixenet');
INSERT INTO `estacio` (`idEstacio`,`nomEstacio`) VALUES (72302,'Sant Joan Despí');
INSERT INTO `estacio` (`idEstacio`,`nomEstacio`) VALUES (79304,'Sant Jordi Desvalls');
INSERT INTO `estacio` (`idEstacio`,`nomEstacio`) VALUES (78502,'Sant Martí Sesgueioles');
INSERT INTO `estacio` (`idEstacio`,`nomEstacio`) VALUES (77104,'Sant Martí de Centelles');
INSERT INTO `estacio` (`idEstacio`,`nomEstacio`) VALUES (79306,'Sant Miquel de Fluvià');
INSERT INTO `estacio` (`idEstacio`,`nomEstacio`) VALUES (78610,'Sant Miquel de Gonteres-Viladecavalls');
INSERT INTO `estacio` (`idEstacio`,`nomEstacio`) VALUES (79602,'Sant Pol de Mar');
INSERT INTO `estacio` (`idEstacio`,`nomEstacio`) VALUES (77113,'Sant Quirze de Besora');
INSERT INTO `estacio` (`idEstacio`,`nomEstacio`) VALUES (72207,'Sant Sadurní d\'Anoia');
INSERT INTO `estacio` (`idEstacio`,`nomEstacio`) VALUES (71600,'Sant Vicenç de Calders');
INSERT INTO `estacio` (`idEstacio`,`nomEstacio`) VALUES (78604,'Sant Vicenç de Castellet');
INSERT INTO `estacio` (`idEstacio`,`nomEstacio`) VALUES (77003,'Santa Perpètua de Mogoda');
INSERT INTO `estacio` (`idEstacio`,`nomEstacio`) VALUES (79608,'Santa Susanna');
INSERT INTO `estacio` (`idEstacio`,`nomEstacio`) VALUES (78504,'Seguers-Sant Pere Sallavinera');
INSERT INTO `estacio` (`idEstacio`,`nomEstacio`) VALUES (71602,'Segur de Calafell');
INSERT INTO `estacio` (`idEstacio`,`nomEstacio`) VALUES (79202,'Sils');
INSERT INTO `estacio` (`idEstacio`,`nomEstacio`) VALUES (71701,'Sitges');
INSERT INTO `estacio` (`idEstacio`,`nomEstacio`) VALUES (71500,'Tarragona');
INSERT INTO `estacio` (`idEstacio`,`nomEstacio`) VALUES (78700,'Terrassa');
INSERT INTO `estacio` (`idEstacio`,`nomEstacio`) VALUES (78710,'Terrassa Est');
INSERT INTO `estacio` (`idEstacio`,`nomEstacio`) VALUES (79607,'Tordera');
INSERT INTO `estacio` (`idEstacio`,`nomEstacio`) VALUES (77111,'Torelló');
INSERT INTO `estacio` (`idEstacio`,`nomEstacio`) VALUES (71503,'Torredembarra');
INSERT INTO `estacio` (`idEstacio`,`nomEstacio`) VALUES (65400,'Tortosa');
INSERT INTO `estacio` (`idEstacio`,`nomEstacio`) VALUES (77305,'Toses');
INSERT INTO `estacio` (`idEstacio`,`nomEstacio`) VALUES (78408,'Tàrrega');
INSERT INTO `estacio` (`idEstacio`,`nomEstacio`) VALUES (65314,'Ulldecona-Alcanar-La Sénia');
INSERT INTO `estacio` (`idEstacio`,`nomEstacio`) VALUES (77307,'Urtx-Alp');
INSERT INTO `estacio` (`idEstacio`,`nomEstacio`) VALUES (78606,'Vacarisses');
INSERT INTO `estacio` (`idEstacio`,`nomEstacio`) VALUES (78607,'Vacarisses-Torreblanca');
INSERT INTO `estacio` (`idEstacio`,`nomEstacio`) VALUES (76004,'Valls');
INSERT INTO `estacio` (`idEstacio`,`nomEstacio`) VALUES (77109,'Vic');
INSERT INTO `estacio` (`idEstacio`,`nomEstacio`) VALUES (71401,'Vila-seca');
INSERT INTO `estacio` (`idEstacio`,`nomEstacio`) VALUES (76002,'Vilabella');
INSERT INTO `estacio` (`idEstacio`,`nomEstacio`) VALUES (71709,'Viladecans');
INSERT INTO `estacio` (`idEstacio`,`nomEstacio`) VALUES (78609,'Viladecavalls');
INSERT INTO `estacio` (`idEstacio`,`nomEstacio`) VALUES (72204,'Vilafranca del Penedès');
INSERT INTO `estacio` (`idEstacio`,`nomEstacio`) VALUES (79311,'Vilajuïga');
INSERT INTO `estacio` (`idEstacio`,`nomEstacio`) VALUES (79308,'Vilamalla');
INSERT INTO `estacio` (`idEstacio`,`nomEstacio`) VALUES (71700,'Vilanova i la Geltrú');
INSERT INTO `estacio` (`idEstacio`,`nomEstacio`) VALUES (79410,'Vilassar de Mar');
INSERT INTO `estacio` (`idEstacio`,`nomEstacio`) VALUES (73009,'Vilaverd');
INSERT INTO `estacio` (`idEstacio`,`nomEstacio`) VALUES (73006,'Vimbodí');
INSERT INTO `estacio` (`idEstacio`,`nomEstacio`) VALUES (73005,'Vinaixa');
